Fix maxmind UDFs for hive 2.3.3 (bigtop)
This fix uses maven-shade plugin class-relocation function (see
https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html)
to enforce maxmind-db dependencies to be linked in the refinery-hive
package. Without the class-relocation, some class loading conflict
happens and an old version of the library is used, leading to a
NoSuchMethodError exception at maxmind Reader instanciation.

Bug: T266322
Change-Id: I3b6bf8d2bac3eefe67c4439c0fea295ccbf4948a