Update RefineTarget inputBasePath matches
While testing json refine with the new Netflow datasource, stored
under /wmf/data/raw, I got this error:

User class threw exception:
java.lang.RuntimeException: Regex (netflow)/hourly/(\d+)/(\d+)/(\d+)/(\d+)
did not match hdfs://analytics-hadoop/wmf/data/raw/event/hourly/2018/02/03/07
when attempting to extract capture group keys.

The event datasource is the first subdir of /wmf/data/raw, and of
course it fails to match the regexp. The netflow datasource is a special
case since it lists one topic only (called 'netflow') and there
is no parent directory.

Bug: T181036
Change-Id: I0a9acd6ca80388318395494c5408509a56f39741